default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host:     <%= ENV['DB_HOST'] %>
  port:     <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME'] %>
  database: search_github_development

test:
  <<: *default
  host:     <%= ENV['DB_HOST'] %>
  port:     <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME'] %>
  database: search_github_test

production:
  url: <%= ENV['DATABASE_URL'] %>
